apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockapi-deployment
  labels:
    app: mockapi
spec:
  selector:
    matchLabels:
      app: mockapi
  template:
    metadata:
      labels:
        app: mockapi
    spec:
      containers:
      - name: mockapi-container
        image: {REPLACE WITH YOUR AMAZON AWS Container address}/ethauth/mockapi:1.0-SNAPSHOT
        ports:
        - containerPort: 9080

---
apiVersion: v1
kind: Service
metadata:
  name: mockapi-service
spec:
  type: NodePort
  selector:
    app: mockapi
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000
